version: "3"

services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=data
    volumes:
      - ../../database:/data/db
      - ../../import_data:/import_data
    user: "1000:1000"

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://database:27017/checklist
      - ME_CONFIG_SITE_BASEURL=/mongo
    restart: unless-stopped

  backend:
    image: node:16
    environment:
      - DATABASE_URL=mongodb://database:27017/checklist
    volumes:
      - ../back:/back
    command: bash -c "cd /back && npm start"

  frontend:
    image: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ../front/dist/shared-checklist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
